-- select id,nome,codigo,categoria,altura,peso,hp,ataque,defesa,
-- especial_ataque,especial_defesa,velocidade,descricao from pokemons;
-- SELECT ataque,especial_ataque,defesa,especial_defesa FROM pokemons;
-- SELECT  nome,categoria, ataque FROM pokemons ORDER BY ataque;
-- SELECT peso,altura, (peso/(altura*altura)) FROM pokemons;
-- SELECT peso,altura, (peso/(altura*altura)) FROM pokemons ORDER BY (peso/(altura*altura))DESC;
-- SELECT nome,CHARACTER_LENGTH(nome) FROM pokemons ORDER BY CHARACTER_LENGTH(nome) desc;